name: Build and Push Docker Image
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: false
        default: 'update-wallet-ux'

jobs:
  build-docker-arm:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: linux/arm64
            runner: macos-latest
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Build frontend locally for act
        run: |
          if [ -d "frontend/dist" ]; then
            echo "Using existing frontend/dist directory"
            ls -la frontend/dist/
          else
            echo "Building frontend locally for act..."
            npm install -g pnpm
            npm run build:frontend
            echo "Frontend build completed:"
            ls -la frontend/dist/
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (${{ matrix.arch }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/eltor:latest-${{ matrix.arch }}
            ${{ secrets.DOCKER_USERNAME }}/eltor:${{ github.sha }}-${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
