name: Build eltord Binary
on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Choose which platform to build'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - linux
          - windows
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  # release:
  #   types: [created] # Trigger on GitHub release creation

permissions:
  contents: write # Needed for uploading release assets

jobs:
  build-linux:
    name: Build eltord - Linux-x86_64
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_target == 'all' || github.event.inputs.build_target == 'linux' || github.event.inputs.build_target == '' }}
    env:
      PLATFORM_OS: ubuntu-latest
      PLATFORM_TARGET: x86_64-unknown-linux-gnu
      PLATFORM_BIN: eltord
      PLATFORM_OS_NAME: Linux-x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ env.PLATFORM_TARGET }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libssl-dev \
            libsqlite3-dev \
            build-essential \
            curl \
            wget \
            git \
            autoconf \
            automake \
            libtool \
            zlib1g-dev \
            libevent-dev \
            libscrypt-dev \
            make \
            patch \
            flex \
            bison \
            unzip \
            clang

      - name: Clone git dependencies
        run: |
          git clone https://github.com/el-tor/eltor.git /home/runner/code/eltor
          git clone https://github.com/lightning-node-interface/lni.git /home/runner/code/lni
          git clone https://github.com/el-tor/libeltor-sys.git /home/runner/code/libeltor-sys
          git clone https://github.com/el-tor/libeltor.git /home/runner/code/libeltor
          git clone https://github.com/el-tor/eltord.git /home/runner/code/eltord

      - name: Checkout specific branches
        run: |
          cd /home/runner/code/eltord && git checkout master
          cd /home/runner/code/lni && git checkout search

      - name: Build libeltor-sys
        run: |
          cd /home/runner/code/libeltor-sys
          ls -la && ls -la scripts
          chmod +x scripts/copy.sh scripts/build.sh
          ./scripts/copy.sh
          mkdir -p patches libtor-src/patches
          touch patches/.keep libtor-src/patches/.keep
          cargo build --release --verbose --target ${{ env.PLATFORM_TARGET }} --features vendored-openssl

      - name: Build eltord
        run: |
          cd /home/runner/code/eltord
          cargo build --release --verbose --target ${{ env.PLATFORM_TARGET }} --features vendored-openssl

      - name: Rename binaries
        run: |
          mkdir -p artifacts/${{ env.PLATFORM_OS_NAME }}
          mv /home/runner/code/eltord/target/${{ env.PLATFORM_TARGET }}/release/eltor artifacts/${{ env.PLATFORM_OS_NAME }}/eltord

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eltord-${{ env.PLATFORM_OS_NAME }}
          path: |
            artifacts
          if-no-files-found: error

      - name: Release binary
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/${{ env.PLATFORM_OS_NAME }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build eltord - Windows-x86_64
    runs-on: windows-latest
    if: ${{ github.event.inputs.build_target == 'all' || github.event.inputs.build_target == 'windows' || github.event.inputs.build_target == '' }}
    env:
      PLATFORM_OS: windows-latest
      PLATFORM_TARGET: x86_64-pc-windows-gnu
      PLATFORM_BIN: eltord.exe
      PLATFORM_OS_NAME: Windows-x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ env.PLATFORM_TARGET }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Windows dependencies
        run: |
          # Install MSYS2 which provides MinGW and is more reliable
          choco install -y msys2
          
          # Install basic build tools
          choco install -y git

      - name: Install MSYS2 packages
        run: |
          # Install autotools and build dependencies through MSYS2
          C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
          C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm autotools automake autoconf libtool make pkg-config mingw-w64-x86_64-toolchain mingw-w64-x86_64-openssl mingw-w64-x86_64-zlib"

      - name: Set Windows environment
        run: |
          # Add MSYS2 MinGW to PATH (more reliable than standalone MinGW)
          echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH
          echo "C:\msys64\usr\bin" >> $env:GITHUB_PATH
          
          # Set Rust build flags for GNU target
          echo "RUSTFLAGS=-C target-feature=+crt-static" >> $env:GITHUB_ENV

      - name: Verify build tools
        run: |
          # Check that required tools are available
          which gcc || echo "gcc not found"
          which make || echo "make not found" 
          which autoconf || echo "autoconf not found"
          which automake || echo "automake not found"
          which aclocal || echo "aclocal not found"
          which libtool || echo "libtool not found"
        shell: bash

      - name: Clone git dependencies
        run: |
          git clone https://github.com/el-tor/eltor.git D:/a/code/eltor
          git clone https://github.com/lightning-node-interface/lni.git D:/a/code/lni
          git clone https://github.com/el-tor/libeltor-sys.git D:/a/code/libeltor-sys
          git clone https://github.com/el-tor/libeltor.git D:/a/code/libeltor
          git clone https://github.com/el-tor/eltord.git D:/a/code/eltord
        shell: bash

      - name: Checkout specific branches
        run: |
          cd D:/a/code/eltord && git checkout master
          cd D:/a/code/lni && git checkout search
        shell: bash

      - name: Build libeltor-sys
        run: |
          cd D:/a/code/libeltor-sys
          # Ensure autotools are available
          export PATH="/c/msys64/usr/bin:/c/msys64/mingw64/bin:$PATH"
          ls -la && ls -la scripts
          chmod +x scripts/copy.sh scripts/build.sh
          ./scripts/copy.sh
          mkdir -p patches libtor-src/patches
          touch patches/.keep libtor-src/patches/.keep
          cargo build --release --verbose --target ${{ env.PLATFORM_TARGET }} --features vendored-openssl
        shell: bash

      - name: Build eltord
        run: |
          cd D:/a/code/eltord
          cargo build --release --verbose --target ${{ env.PLATFORM_TARGET }} --features vendored-openssl
        shell: bash

      - name: Rename binaries
        run: |
          mkdir -p artifacts/${{ env.PLATFORM_OS_NAME }}
          mv D:/a/code/eltord/target/${{ env.PLATFORM_TARGET }}/release/eltor.exe artifacts/${{ env.PLATFORM_OS_NAME }}/eltord.exe
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eltord-${{ env.PLATFORM_OS_NAME }}
          path: |
            artifacts
          if-no-files-found: error

      - name: Release binary
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/${{ env.PLATFORM_OS_NAME }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
